version: '3'
services:
  api:
    build: .
    working_dir: /app/server
    command: ['pipenv', 'run', 'gunicorn', 'server.asgi:application', '-k', 'uvicorn.workers.UvicornWorker', '-b', '0.0.0.0:8000', '--capture-output']
    volumes:
      - .:/app
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgres://root:root@db:5433/api
      - DJANGO_SETTINGS_MODULE=server.settings.docker_production
      - SECRET_KEY=hogefuga
      - LANG=ja_JP.utf8
      - LC_ALL=ja_JP.utf8
    ports:
      - "8080:8000"
  db:
    image: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - '5433:5432'
