openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/genres/:
    get:
      operationId: listGenres
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genre'
          description: ''
      tags:
      - api
  /api/v1/genres/{id}/:
    get:
      operationId: retrieveGenre
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this genre.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
          description: ''
      tags:
      - api
  /api/v1/works/:
    get:
      operationId: listWorks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Work'
          description: ''
      tags:
      - api
  /api/v1/works/{id}/:
    get:
      operationId: retrieveWork
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this work.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
          description: ''
      tags:
      - api
  /api/v1/works/{work_pk}/comments/:
    get:
      operationId: listComments
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
          description: ''
      tags:
      - api
    post:
      operationId: createComment
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Comment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
          description: ''
      tags:
      - api
  /api/v1/works/{work_pk}/comments/{id}/:
    get:
      operationId: retrieveComment
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
          description: ''
      tags:
      - api
    put:
      operationId: updateComment
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Comment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateComment
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Comment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyComment
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/works/{work_pk}/goods/:
    post:
      operationId: createWork
      description: ''
      parameters:
      - name: work_pk
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Work'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Work'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Work'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
          description: ''
      tags:
      - api
components:
  schemas:
    Genre:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        works:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              title:
                type: string
                maxLength: 255
              description:
                type: string
              genre:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  title:
                    type: string
                    maxLength: 255
                  bg_color:
                    type: string
                    pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
                    maxLength: 18
                readOnly: true
              team:
                type: object
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 255
                required:
                - name
                readOnly: true
              thumbnail:
                type: string
                format: binary
              goods:
                type: integer
              download_link:
                type: string
                nullable: true
                format: uri
                pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
                  d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\\
                  d?)){3}|\\[[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF\
                  0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\\
                  .(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\\
                  d{2,5})?(?:[/?#][^\\s]*)?\\z"
                maxLength: 255
              comments:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    created_at:
                      type: string
                      format: date-time
                      readOnly: true
                    name:
                      type: string
                      maxLength: 255
                    text:
                      type: string
                    work:
                      type: integer
                  required:
                  - name
                  - text
                  - work
                readOnly: true
              tags:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    name:
                      type: string
                    color:
                      type: string
                      pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
                      maxLength: 18
                  required:
                  - name
                readOnly: true
              media_assets:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    youtube_video_id:
                      type: string
                      nullable: true
                      maxLength: 16
                    image:
                      type: string
                      format: binary
                      nullable: true
                    sketchfab_embed_html:
                      type: string
                      nullable: true
                    soundcloud_embed_html:
                      type: string
                      nullable: true
                    work:
                      type: integer
                  required:
                  - work
                readOnly: true
            required:
            - title
            - thumbnail
        title:
          type: string
          maxLength: 255
        bg_color:
          type: string
          pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
          maxLength: 18
      required:
      - works
    Work:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        genre:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            title:
              type: string
              maxLength: 255
            bg_color:
              type: string
              pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
              maxLength: 18
          readOnly: true
        team:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              maxLength: 255
          required:
          - name
          readOnly: true
        thumbnail:
          type: string
          format: binary
        goods:
          type: integer
        download_link:
          type: string
          nullable: true
          format: uri
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
            d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\d?)){3}|\\\
            [[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
            -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
            -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{2,5})?(?:[/?#][^\\\
            s]*)?\\z"
          maxLength: 255
        comments:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              created_at:
                type: string
                format: date-time
                readOnly: true
              name:
                type: string
                maxLength: 255
              text:
                type: string
              work:
                type: integer
            required:
            - name
            - text
            - work
          readOnly: true
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
              color:
                type: string
                pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
                maxLength: 18
            required:
            - name
          readOnly: true
        media_assets:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              youtube_video_id:
                type: string
                nullable: true
                maxLength: 16
              image:
                type: string
                format: binary
                nullable: true
              sketchfab_embed_html:
                type: string
                nullable: true
              soundcloud_embed_html:
                type: string
                nullable: true
              work:
                type: integer
            required:
            - work
          readOnly: true
      required:
      - title
      - thumbnail
    Comment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        text:
          type: string
        work:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            title:
              type: string
              maxLength: 255
            description:
              type: string
            thumbnail:
              type: string
              format: binary
            goods:
              type: integer
            download_link:
              type: string
              nullable: true
              format: uri
              pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4]\\\
                d|1\\d?\\d?|[1-9]\\d?)(?:\\.(?:0|25[0-5]|2[0-4]\\d|1\\d?\\d?|[1-9]\\\
                d?)){3}|\\[[0-9a-f:.]+\\]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1\
                -\uFFFF0-9])?(?:\\.(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1\
                -\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?|localhost))(?::\\d{2,5})?(?:[/?#][^\\\
                s]*)?\\z"
              maxLength: 255
            genre:
              type: integer
              nullable: true
            team:
              type: integer
            tags:
              type: array
              items:
                type: integer
          required:
          - title
          - thumbnail
          - team
          - tags
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - name
      - text
