# Generated by Django 3.0.7 on 2020-07-11 03:15

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unityroom_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Genre', max_length=255)),
                ('bg_color', colorfield.fields.ColorField(default='#ff0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketchfab_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='None')),
                ('type_choice', models.TextField(choices=[('U3D', 'Unity 3D'), ('U2D', 'Unity 2D'), ('VID', 'VIDEO'), ('M3D', 'MODEL 3D'), ('OTHER', 'OTHER')], default='OTHER')),
                ('card_image', models.ImageField(upload_to='images/system/')),
                ('goods', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Genre')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Work')),
            ],
        ),
    ]
