# Generated by Django 3.0.6 on 2020-06-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
