# Generated by Django 3.0.6 on 2020-06-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Game'),
        ),
        migrations.AddField(
            model_name='work',
            name='model3d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Model3D'),
        ),
        migrations.AddField(
            model_name='work',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Video'),
        ),
    ]
