# Generated by Django 3.0.7 on 2020-07-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
