# Generated by Django 3.0.7 on 2020-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200712_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='gltf_bin',
            field=models.FileField(default='', upload_to='3dmodels/'),
            preserve_default=False,
        ),
    ]
