# Generated by Django 3.0.7 on 2020-07-12 11:49

from django.db import migrations, models
import works.validators


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_model3d_gltf_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='gltf',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='gltf_bin',
        ),
        migrations.AddField(
            model_name='model3d',
            name='glb',
            field=models.FileField(default='', upload_to='3dmodels/', validators=[works.validators.validate_is_glb]),
            preserve_default=False,
        ),
    ]
