# Generated by Django 3.0.7 on 2020-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200712_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(default='\n<details>\n  <summary class="Subject">作品紹介</summary>\n  <p class="Paragraph">\n    <b>作品説明：</b><br>\n     このゲームは、探索型2dアクションゲームです。<br>\n    マップを探索して鍵を集めて先に進み、ボスを倒せばゲームクリアです。\n  </p>\n  <p class="Paragraph">\n    <b>使用ツール：</b><br>\n    Unity 2019.3.14f1\n  </p>\n</details>\n<details>\n  <summary class="Subject">操作方法</summary>\n  <ul class="Paragraph">\n    <li>矢印← ... 左に移動</li>\n    <li>矢印→ ... 右に移動</li>\n    <li>矢印↑ ... ジャンプ</li>\n    <li>矢印↓ ... (すり抜け床の上にいるとき)床をすり抜ける</li>\n  </ul>\n  <p class="Paragraph">\n    敵は踏みつけたら倒せます。(マリオの踏みつけと同じ)<br>\n    敵に当たると体力が減ります。<br>\n    体力が無くなると、セーブポイントに戻されます。<br>\n    フルーツを取ると体力が回復します。<br>\n    <br>\n    鍵を取ると進める場所が増えます。<br>\n    マップ上には、アクションを増やすアイテムが存在します。<br>\n    もし先に進めなくなったら、アイテムを探してみましょう。\n  </p>\n</details>\n<details>\n  <summary class="Subject">制作者からひとこと</summary>\n  <p class="Paragraph">\n    <b>Kuroki：</b><br>\n    プレイヤー･敵キャラを作りました。<br>\n    このゲームで使ったUnityアセット「Pixel Adventure」は、<br>\n    無料かつ素材が豊富なのでぜひ使ってみてください。<br>\n    <b>Crucio：</b><br>\n    ステージ･ギミックを作りました。\n  </p>\n</details>\n'),
        ),
    ]
