# Generated by Django 3.0.7 on 2020-07-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20200713_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Video'),
        ),
    ]
