# Generated by Django 3.0.7 on 2020-07-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_work_video'),
        ('works', '0007_auto_20200714_0122'),
    ]

    operations = [
    ]
