# Generated by Django 3.0.7 on 2020-07-15 04:11

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models
import works.validators


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_merge_20200715_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mp4',
            field=models.ImageField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[works.validators.validate_is_mp4, cloudinary_storage.validators.validate_video]),
        ),
    ]
