# Generated by Django 3.0.7 on 2020-07-16 00:19

from django.db import migrations, models
import works.validators


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_merge_20200715_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='vrm',
            field=models.FileField(blank=True, null=True, upload_to='3dmodels/', validators=[works.validators.validate_is_vrm]),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='glb',
            field=models.FileField(blank=True, null=True, upload_to='3dmodels/', validators=[works.validators.validate_is_glb]),
        ),
    ]
