# Generated by Django 3.0.7 on 2020-07-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20200716_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveschedule',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
