# Generated by Django 3.2.5 on 2021-07-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20210703_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(blank=True, max_length=16, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/system')),
                ('sketchfab_embed_html', models.TextField(blank=True, null=True)),
                ('soundcloud_embed_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LiveSchedule',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='card_image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='work',
            name='game',
        ),
        migrations.RemoveField(
            model_name='work',
            name='model3d',
        ),
        migrations.RemoveField(
            model_name='work',
            name='type_choice',
        ),
        migrations.RemoveField(
            model_name='work',
            name='video',
        ),
        migrations.AddField(
            model_name='work',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Model3D',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='works.work'),
        ),
    ]
