# Generated by Django 3.2.5 on 2021-07-10 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0014_auto_20210710_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='sketchfab_embed_html',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='soundcloud_embed_html',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
