# Generated by Django 3.2.5 on 2021-07-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20210710_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='No description...'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='sketchfab_embed_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='soundcloud_embed_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
