# Generated by Django 3.2.5 on 2021-07-15 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20210714_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
