# Generated by Django 3.2.5 on 2021-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_work_work_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='downloaded_count',
            field=models.IntegerField(default=0),
        ),
    ]
